cd c:\xampplite\php
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 1
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 2
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 3
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 4
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 5
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 6
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 7
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 8
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 9
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 10
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 11
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 12
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 13
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 14
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 15
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 16
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 17
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 18
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 19
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 20 
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 21
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 22
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 23
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 24
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 25
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 26
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 27
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 28
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 29
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 30
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 31
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 32
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 33
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 34
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 35
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 36
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 37
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 38
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 39
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 40
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 41
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 42
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 43
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 44
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 45
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 46
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 47
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 48
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 49
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 50
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 51
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 52
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 53
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 54
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 55
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 56
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 57
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 58
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 59
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 60
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 61
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 62
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 63
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 64
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 65
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 66
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 67
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 68
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 69
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 70
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 71
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 72
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 73
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 74
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 75
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 76
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 77
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 78
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 79
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 80
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 81
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 82
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 83
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 84
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 85
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 86
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 87
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 88
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 89
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 90
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 91
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 92
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 93
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 94
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 95
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 96
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 97
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 98
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 99
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 100
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 101
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 102
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 103
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 104
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 105
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 106
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 107
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 108
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 109
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 110
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 111
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 112
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 113
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 114
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 115
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 116
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 117
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 118
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 119
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 120 
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 121
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 122
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 123
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 124
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 125
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 126
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 127
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 128
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 129
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 130
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 131
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 132
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 133
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 134
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 135
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 136
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 137
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 138
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 139
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 140
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 141
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 142
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 143
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 144
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 145
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 146
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 147
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 148
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 149
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 150
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 151
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 152
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 153
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 154
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 155
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 156
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 157
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 158
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 159
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 160
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 161
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 162
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 163
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 164
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 165
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 166
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 167
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 168
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 169
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 170
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 171
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 172
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 173
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 174
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 175
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 176
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 177
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 178
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 179
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 180
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 181
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 182
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 183
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 184
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 185
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 186
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 187
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 188
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 189
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 190
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 191
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 192
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 193
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 194
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 195
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 196
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 197
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 198
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 199
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 200
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 201
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 202
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 203
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 204
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 205
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 206
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 207
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 208
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 209
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 210
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 211
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 212
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 213
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 214
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 215
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 216
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 217
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 218
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 219
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 220 
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 221
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 222
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 223
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 224
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 225
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 226
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 227
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 228
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 229
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 230
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 231
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 232
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 233
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 234
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 235
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 236
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 237
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 238
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 239
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 240
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 241
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 242
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 243
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 244
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 245
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 246
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 247
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 248
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 249
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 250
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 251
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 252
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 253
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 254
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 255
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 256
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 257
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 258
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 259
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 260
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 261
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 262
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 263
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 264
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 265
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 266
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 267
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 268
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 269
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 270
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 271
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 272
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 273
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 274
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 275
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 276
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 277
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 278
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 279
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 280
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 281
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 282
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 283
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 284
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 285
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 286
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 287
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 288
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 289
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 290
php -f c:\xampplite\htdocs\HCMPv2\index.php rtk_management kemsa_district_reports 291